### ISSUE TITLE
Printer never connects

### ISSUE THREAD

**Issue by TeaVirus** [kennethjiang/OctoPrint-Anywhere#25] opened 2017-07-29 20:29 UTC
I'm able to "pair" the printer from Octoprint and it shows up in the dashboard.  The problem is that it continually shows "Waiting for camera feed..." and never gets any further.  Any recommendations?

**Comment by kennethjiang** [comment] 2017-07-31 00:14
Hi @TeaVirus The service that my plugin is using has started to throttle the requests because of the unexpected amount of signups to my plugin. I'm working with them to solve this issue. I will notify you once I get this figured out, probably in a few days to a week. If it still doesn't work after that, I will do some further diagnosis to see what could be the cause.

**Comment by kennethjiang** [comment] 2017-08-06 15:34
@TeaVirus I have solved the issues with our backend service. For the past several days it has been very stable.

I'm closing this issue now but feel free to reopen it if you still run into problems.

**Comment by nkuck** [comment] 2019-01-04 15:46
I am having the same issue. Is there a fix? Thanks for the help.

**Comment by kennethjiang** [comment] 2019-01-04 20:21
I suspect your Pi doesn't have a reliable internet connection. Can you send me `octoprint.log` so that I can take a look? @nkuck

**Comment by nkuck** [comment] 2019-01-04 20:24
Thanks, but got it working a couple of hours ago. Registered a new printer and deleted the old one.

**Comment by kennethjiang** [comment] 2019-01-04 21:01
Glad to know it worked for you.

**Closed by kennethjiang** 2019-01-04 21:01 UTC
