### ISSUE TITLE
OctoPrint-Anywhere installs fine but isn't seen as a plugin

### ISSUE THREAD

**Issue by enotsone** [kennethjiang/OctoPrint-Anywhere#56] opened 2018-04-22 20:48 UTC
Using OctoPrint 1.3.8 (OctoPi 0.14) and using the plugin manager to install OctoPrint-Anywhere (0.6.1) the install goes fine with no errors.  When it is done, a dialog comes up saying 'Installed: unknown' and when the reboot of the OctoPrint service is done, the OctoPrint-Anywhere doesn't show up under the tool menu.  When I go to install it again, it sees that it was already installed and does a 'force' install, yet it still shows as 'Installed: unknown' and when rebooted, nothing shows up.

During the first install, it stated that my pip version was a bit old, so I updated it but still no joy.
Matt
![capture](https://user-images.githubusercontent.com/38634764/39099709-f3ef6986-464c-11e8-82a3-90f6fd89213f.PNG)
![capture2](https://user-images.githubusercontent.com/38634764/39099710-f3fbd31a-464c-11e8-8df6-a7d168b2f14d.PNG)

**Comment by kennethjiang** [comment] 2018-04-23 16:06
It looks like OctoPrint 1.3.8 somehow broke the compatibility. Will working on fixing it asap.

**Comment by ironjoe13** [comment] 2018-08-21 17:57
I have this same problem with 0.15. octopi and 1.3.8 Octoprint

**Comment by kennethjiang** [comment] 2018-08-22 01:34
Hi @ironjoe13 Can you post your `octoprint.log` file here? Refer to [this document](https://discourse.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299) for how to do download the log file.

**Comment by kennethjiang** [comment] 2018-08-22 15:25
Awesome thanks!

**Comment by ironjoe13** [comment] 2018-08-22 17:46
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/2311441/octoprint.log)

**Comment by kennethjiang** [comment] 2018-08-22 19:35
From your `octoprint.log`, the installation of OctoPrint Anywhere succeeded at 2018-08-21 17:24:27 (UTC), and the status of the plugin changed from `disabled` to `active` after OctoPrint restarted.

Can you see OctoPrint Anywhere config page as below?
<img width="1161" alt="screen shot 2018-08-22 at 12 34 24 pm" src="https://user-images.githubusercontent.com/779786/44486209-c717ae80-a607-11e8-8ef8-5a94f01e1045.png">

**Comment by ironjoe13** [comment] 2018-08-22 19:50
It does not show up. I just tried to install it again after it was uninstalled yesterday and got this with the Unknown plugin notice:
![anywhere](https://user-images.githubusercontent.com/33383148/44486926-8bd2ab00-a61a-11e8-8966-2d1ffb1ab0f4.JPG)

**Comment by ironjoe13** [comment] 2018-08-22 19:52
[plugin_pluginmanager_console.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/2311782/plugin_pluginmanager_console.log)

**Comment by kennethjiang** [comment] 2018-08-23 00:55
The failed installation happened at  2018-08-22 19:46:20 UTC. The succeeded installation in your previous `octoprint.log` happened at 2018-08-21 17:24:27 UTC. Were these 2 installations on the same OctoPrint (1.3.8 I assume)?

What did you see after the succeeded (at least according to `octoprint.log`) installation at  2018-08-21 17:24:27 UTC? Did you still not see the OctoPrint Anywhere config dialog? Was it why you had to uninstall it and install it again at 2018-08-22 19:46:20 UTC ?

**Comment by ironjoe13** [comment] 2018-08-23 10:26
Octoprint Anywhere was visible and working on the 1.3.9 install onto separate Raspbian system. Yes I did uninstall and reinstall, no change.
The "successful" install at 17:24 was followed by : 
2018-08-21 17:31:58,020 - tornado.access - WARNING - 403 POST /api/plugin/anywhere (127.0.0.1) 14.19ms
2018-08-21 17:45:49,075 - tornado.access - WARNING - 403 POST /api/plugin/anywhere (127.0.0.1) 14.73ms
It did not show up after that installation either, after saying it was "unknown plugin"

**Comment by kennethjiang** [comment] 2018-08-23 15:26
Thank you so much for catching those 403 errors.

There are some existing OctoPrint issues that may be similar to this. In https://github.com/foosel/OctoPrint/issues/2184 it was suggested it could be caused by a permission issue in `/tmp/` folder.

https://github.com/foosel/OctoPrint/issues/1881 suggests that this issue should be fixed in 1.3.9

If none of these solutions helped, feel free to log a bug for OctoPrint at https://github.com/foosel/OctoPrint/issues/new . I will be happy to provide whatever info @foosel needs to get to the bottom of it.

The second error (-3 exit code by decompressing) seems like a separate issue. It also seems like a temporary error. Have you seen this error dialog more than once?

**Comment by ironjoe13** [comment] 2018-08-23 18:00
I have gotten the temporary error before, I haven't figured out why as of yet.... I believe it has something to do with when I am on YouTube on one browser page, and Octoprint on another page(separate displays, displaying both pages at once)
I will update to 1.3.9 and let you know what happens

**Comment by kennethjiang** [comment] 2018-11-05 22:44
@ironjoe13 are you still experiencing this error?

**Comment by onemadpunk** [comment] 2018-11-07 12:30
Hi there i am having trouble installing your plugin as well. andy help would be appreciated as it seems a great addition to octoprint.

Installing plugin "OctoPrint Anywhere" from https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip install https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip --no-cache-dir
Collecting https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip
Downloading https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

[plugin_pluginmanager_console.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/2557341/plugin_pluginmanager_console.log)

Thanks in advance for your help
octoprint Version 1.3.9
octopi Version 0.15.1

**Comment by kennethjiang** [comment] 2018-11-07 13:43
Hi @onemadpunk , the log file shows that it failed to download the plugin zip file from github. The most likely cause was that your Pi couldn't connect to internet at that time. Please make sure your Pi can connect to internet and try it again. Please note that it's possible that your computer can connect to internet but your Pi can't. So the best way to test its internet connection is to ssh to the Pi and test from there.

**Comment by onemadpunk** [comment] 2018-11-07 14:37
Hi there 

Updated the PIP to 18 not sure what that is but it was the error on screen
/home/pi/oprint/bin/python -m pip install --upgrade pip

it then installed the plugin.

in octoprint settings i only see
PLUGINS
Action Command Prompt
Bed Leveling Plugin
CuraEngine (<= 15.04)

if i go to plugin manager i can see your plugin installed and enabled
OctoPrint Anywhere (0.9.0)
Control your OctoPrint from anywhere, using your smart phone
 Homepage  AGPLv3  Kenneth Jiang  

however I can see nowhere to follow your setup after install. it did ask me to restart which i have done.

thanks for your quick reply it is nice to see you really do support your work, its much appreciated

**Comment by onemadpunk** [comment] 2018-11-07 19:39
Hi there I have the issue that it is now showing as installed in plugin manager but not seen anywhere else. I cant access the plug in. 

It does not show on the plug in list. and a did not get a set up wizard. I have tried re installing but still the same issue.

Any idea what I am doing wrong ?

Thanks again

**Comment by kennethjiang** [comment] 2018-11-07 21:21
Oh sorry I thought your issue was about being unable to install. Re-opening this issue.
Did you see the OctoPrint Anywhere settings page, as in the screenshot attached?
<img width="1440" alt="screen shot 2018-11-07 at 1 20 12 pm" src="https://user-images.githubusercontent.com/779786/48161646-eb426d80-e28f-11e8-88f9-c895b79cba0d.png">

**Comment by onemadpunk** [comment] 2018-11-07 22:03
![annotation 2018-11-07 220229](https://user-images.githubusercontent.com/21010803/48163902-e35aeb80-e2d8-11e8-90ca-07776e2cb408.jpg)

Hi there I hope this helps show the issue. 
Thanks
Steven

**Comment by kennethjiang** [comment] 2018-11-07 23:57
Ah I got it now. Thank you so much @onemadpunk for the screenshot!
Can you send your `octoprint.log` file to k@getanywhere.io? I'm hoping that file can provide some insights.

**Comment by onemadpunk** [comment] 2018-11-08 06:19
Hi there I have emailed the file as requested, thanks again for the help.

**Comment by kennethjiang** [comment] 2018-11-09 21:06
Thank you so much @onemadpunk for letting me debug it on your pi and figured this out.

@ironjoe13 @enotsone  if you are still having this issue, you can try the solution that worked for @onemadpunk 
- SSH to your Pi.
- run `/home/pi/oprint/bin/pip uninstall raven`
- Uninstall and re-install OctoPrint Anywhere plugin.

**Closed by kennethjiang** 2018-11-09 21:06 UTC
