### ISSUE TITLE
Temperature graph not shown with "Tempsgraph Plugin (0.2.2)"

### ISSUE THREAD

**Issue by chixxi** [kennethjiang/OctoPrint-Anywhere#13] opened 2017-07-05 12:40 UTC
After installing you plugin I did not see a temperature graph anymore in the user interface of octoprint. After uninstalling the plugin "Tempsgraph Plugin (0.2.2)" I see the graph again.

But without your plugin installed and only "Tempsgraph Plugin (0.2.2)" installed, it works fine. 

Could you check how this behaves in your case? Could that be related?

**Comment by kennethjiang** [comment] 2017-07-05 13:15
@chixxi I think it's very possible this issue is caused by some conflict between my plugin and Tempsgraph Plugin. I will look into it when I get a chance.

**Comment by chixxi** [comment] 2017-07-05 13:20
Thanks a lot for the quick feedback and let me know if you need further testing.

**Comment by kennethjiang** [comment] 2017-07-20 18:04
Hi @chixxi , sorry for the delay.

I installed Tempsgraph and looked into this issue. From Javascript console it appears to be a Javascript error from Tempsgraph plugin. Attached is the screenshot.

This error might have been caused the installation of Anywhere plugin, but without knowing how Tempsgraph works, trying to debug this issue for it is like finding a needle in a haystack for me.

I'd recommend you to submit an issue to Tempsgraph plugin developers. I'm sure they will be more efficient in finding out where the problem is.

<img width="1150" alt="screen shot 2017-07-20 at 10 59 59 am" src="https://user-images.githubusercontent.com/779786/28431858-a9e03604-6d3a-11e7-8791-1cc76ced1952.png">

**Comment by kennethjiang** [comment] 2017-09-19 00:50
@chixxi I'm closing this issue assuming that you have worked with Tempsgraph team to sort this out. However if you have reason to believe this is an issue caused by Anywhere plugin, please re-open it and provide additional info. Thanks!

**Closed by kennethjiang** 2017-09-19 00:50 UTC
Labels: bug
